let menuData=[];let siteLabel={};$(document).ready(function(){$.ajax({url:'/AHIMSG5/hissso/portal/json/menu.json',type:'GET',dataType:'json',success:function(data){menuData=data;createMenu(menuData.menu,document.getElementById("menu"));initAfterMenuJsonLoad()}});document.getElementById('closeModalBtn').addEventListener('click',function(){var modal=document.getElementById('pdfModal');modal.style.display='none'});$.ajax({url:'/AHIMSG5/hissso/portal/json/label.json',type:'GET',dataType:'json',success:function(data){siteLabel=data;var lang=localStorage.getItem('siteLanguage');if(lang!=undefined)
$('#lang').val(lang);else lang='en';if(lang=='en')
initLanguageLabels();else languageChange()}})});$(window).unload(function(){});function initLanguageLabels(){var lang=$('#lang').val();if(lang==undefined)
lang='en';$("[data-lang-key]").each(function(){var key=$(this).attr("data-lang-key");var val='';if(siteLabel[key]!=undefined)
val=siteLabel[key][lang];if(val==undefined){val=siteLabel[key].en}
if(val==undefined)
val="";$(this).html(val)})}
function initAfterMenuJsonLoad(){console.log("inside >>initAfterMenuJsonLoad ");const $submenuItems=$('.ruby-menu a');$submenuItems.on('click',function(event){event.preventDefault();const submenuId=$(this).data('submenu-id');const menuType=$(this).data('submenu-type');const menuObj=findMenuById(submenuId,menuData.menu);setMenuDetailsByMenuId(menuObj);console.log("menuobjj"+setMenuDetailsByMenuId(menuObj),menuObj)});displayCircularDetails(0)}
function setMenuDetailsByMenuId(menuObj){console.log("inside >>setMenuDetailsByMenuId   >> ",menuObj.url,menuObj.menuId,menuObj.menuOrder);const $sliderSection=$('#slider');const $contentDiv=$('#submenu-content');if(menuObj!=null){var contentType=menuObj.contentType;localStorage.setItem('ctMenuId',menuObj.menuId);localStorage.setItem('ctMenuType','normal');switch(contentType){case 'html':setMenuBreadCrumb(menuObj.menuId,menuData);$sliderSection.add($("#sociallinks")).add($("#newsSection")).hide();$contentDiv.show();$("#submenu-banner").show();$("#content-display").html(getMenuContentByLang(menuObj));break;case 'url':if(menuObj.url==""||menuObj.url=='#'){url="/AHIMSG5/hissso/Login";window.location.href=url}else window.open(menuObj.url,'_blank');break;case 'files':displayFileDetails(menuObj);break}}}
function setMenuBreadCrumb(menuId,menuData){const menuArray=getMenuHierarchyById(menuId,menuData.menu);let breadcrumb='';menuArray.forEach((item,index)=>{const[id,newtitle]=item.split('###');const menuDataVal=menuData.menu?menuData.menu:menuData;const menuObjVal=findMenuById(id.toString(),menuDataVal);console.log(menuObjVal);const title=getMenuTitleByLang(menuObjVal);if(index!==menuArray.length-1){breadcrumb+=`<a style="cursor: pointer;" onclick="goToParentPage('${id}')" class="text-white opacity-75">${title} &nbsp;&nbsp;</a><i class="fa-solid fa-arrow-right text-white mx-1"></i> &nbsp;&nbsp;`}else{breadcrumb+=`<a style="cursor: pointer;" onclick="goToPage('${id}')" class="text-white opacity-75">${title}</a>`}});$("#submenu-breadcrumb").html(breadcrumb)}
function findMenuById(menuId,menuData){if(menuData)
for(const menu of menuData){if(menu.menuId==menuId){return menu}
if(menu.submenu&&menu.submenu.length>0){const foundInSubmenu=findMenuById(menuId,menu.submenu);if(foundInSubmenu){return foundInSubmenu}}}
return null}
function getMenuHierarchyById(menuId,menus=menuData.menu,path=[]){for(const menu of menus){if(menu.menuId==menuId){return[...path,`${menu.menuId}###${menu.title}`]}
if(menu.submenu&&menu.submenu.length>0){const result=getMenuHierarchyById(menuId,menu.submenu,[...path,`${menu.menuId}###${menu.title}`]);if(result){return result}}}
return null}
function getAllSubmenuTitlesByParentId(parentMenuId,menus=menuData.menu){console.log("inside >>getAllSubmenuTitlesByParentId ");for(const menu of menus){if(menu.menuId==parentMenuId&&menu.submenu){return menu.submenu.map(submenu=>`${submenu.menuId}###${submenu.title}###${submenu.titleHindi}`)}
if(menu.submenu&&menu.submenu.length>0){const result=getAllSubmenuTitlesByParentId(parentMenuId,menu.submenu);if(result.length>0){return result}}}
return[]}
function goToPage(menuId){console.log("inside >>goToPage ");localStorage.setItem('ctMenuId',menuId);localStorage.setItem('ctMenuType','normal');const menuObj=findMenuById(menuId,menuData.menu);setMenuDetailsByMenuId(menuObj)}
function goToParentPage(menuId){console.log("inside >>goToParentPage >> "+menuId);localStorage.setItem('ctMenuId',menuId);localStorage.setItem('ctMenuType','parray');setmenuListByArray(getAllSubmenuTitlesByParentId(menuId,menuData.menu));setMenuBreadCrumb(menuId,menuData.menu)}
function setmenuListByArray(menuArray){let menuList='';menuArray.forEach(item=>{const[id,title,titleHindi]=item.split('###');const contentTitle=getMenuTitleByLangWithTitles(title,titleHindi);menuList+=`<li class="ruby-menu-item"><a style="cursor: pointer;" onclick="goToPage('${id}')" class="ruby-menu-link">${contentTitle}</a></li>`});$('#slider').hide();$('#submenu-content').show();$('#content-display').html(menuList)}
function setFileListByArray(responses,menuObj){console.log("inside >>setFileListByArray ");const displayNames=responses.map(item=>item.displayName);let fileNames=responses.map(function(response){return response.fileName});let menuList='';fileNames.forEach((item,index)=>{let displayName=displayNames[index];menuList+='<li class="ruby-menu-item"><a style="cursor: pointer;" onclick="displayFile(\''+item+'\',\''+displayName+'\')" class="ruby-menu-link"><i style="color:red" class="fa-solid fa-file-pdf"></i>'+displayName+'</a></li>'});$('#slider').hide();$('#submenu-content').show();$('#content-display').html(menuList)}
window.onclick=function(event){if(event.target==modal){modal.style.display="none";iframe.src=""}}
function displayFile(fileName,displayFileName){var fileNamePart=fileName.split('^')[0];var folderNamePart=fileName.split('^')[1];var displayFileName=displayFileName;console.log("displayFileName  "+displayFileName);var fileURL="/CGHSGrievance/FormFlowXACTION?hmode=ftpFileDownload&fileName="+fileNamePart+"&folderName="+folderNamePart+"&isGlobal=1";fetch(fileURL).then(response=>response.blob()).then(blob=>{var blobURL=URL.createObjectURL(blob);var iframe=document.getElementById('pdfIframe');iframe.type="application/pdf";iframe.src=blobURL;var modal=document.getElementById('pdfModal');modal.style.display="block";document.getElementById('pdfModalHeading').innerText=displayFileName}).catch(error=>{console.error('Error fetching the file:',error)})}
document.getElementById('closeModalBtn').addEventListener('click',function(){document.getElementById('pdfModal').style.display='none'});function displayFileDetails(menuObj){try{$.ajax({url:menuObj.url,method:"GET",dataType:"json",success:function(responses){if(!responses||responses.length===0){alert("No records found.");return}
if(responses.length>1){setFileListByArray(responses,menuObj)}else{displayFile(responses[0].fileName,responses[0].displayName)}},error:function(xhr,status,error){console.error("AJAX Error - Status:",status,"Error:",error,"Response:",xhr.responseText)}})}catch(err){console.error("Exception occurred:",err.message);alert("An unexpected error occurred: "+err.message)}}
function displayCircularDetails(groupId,subGroupId){if(groupId){action=createFHashAjaxQuery("/AHIMSG5/hislogin/fetchCircularDetailsLgnFtr?groupId="+groupId+"&subGroupId="+subGroupId)}else{action=createFHashAjaxQuery("/AHIMSG5/hislogin/fetchCircularDetailsLgnFtr?groupId="+0+"&subGroupId="+0)}
var jsonObject={groupId:groupId,subGroupId:subGroupId};console.log("inside displayCircularDetails jsonObject>>>"+JSON.stringify(jsonObject))
var jsonData=window.btoa(JSON.stringify(jsonObject));try{$.ajax({url:action,method:"GET",dataType:"json",success:function(responses){console.log("AJAX Request Successful. CircularDetailsData:",responses);if(responses.length>1){let fileNames=responses.map(function(response){return response.fileName});console.log("File Names Array:",fileNames);responses.forEach(function(response){const fileName=response.fileName;console.log("Processing fileName:",fileName);addRows(responses,groupId)})}else{responses.forEach(function(response){const fileName=response.fileName;addRows(responses,groupId,subGroupId)})}},error:function(xhr,status,error){console.error("AJAX Error - Status:",status,"Error:",error,"Response:",xhr.responseText);alert("An error occurred while processing your request: "+error)}})}catch(err){console.error("Exception occurred:",err.message);alert("An unexpected error occurred: "+err.message)}}
function addRows(responses,groupId,subGroupId){const datalist=document.querySelector(`#datalistId${groupId}`);$('.datalist').html("");responses.forEach(function(data){addRowData(responses,data,groupId,subGroupId)})}
function formatDate(dateTimeStr){const datePart=dateTimeStr.split(" ")[0];const dateObj=new Date(datePart);const weekdays=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];const weekday=weekdays[dateObj.getDay()];const day=dateObj.getDate();const month=months[dateObj.getMonth()];const year=dateObj.getFullYear();return weekday+" "+day+" "+month+" "+year}
function addRowData(responses,data,groupId,subGroupId){console.log(groupId);var description=data&&data.description?data.description.trim():"No Description Available";var fromDate=data&&data.fromDate?formatDate(data.fromDate.trim()):"No Date Available";var fileName=data&&data.fileName?data.fileName.trim():"No File Available";var displayName=data&&data.displayName?data.displayName.trim():"No DisplayName Available";var showFileName=displayName;var folderName="";var urlFileName=fileName.split("^")[0];if(fileName&&fileName!=="No File Available"){let parts=fileName.split("_");if(parts.length>1){let secondPart=parts[1];let splitParts=secondPart.split("^");folderName=splitParts[1]||""}}
var fileURL="/CGHSGrievance/FormFlowXACTION?hmode=ftpFileDownload&fileName="+urlFileName+"&folderName="+folderName+"&isGlobal=1";const datalist=document.querySelector('.datalist');const newListItem=document.createElement('li');newListItem.classList.add('my-3','pt-3');newListItem.innerHTML="<label class='text-decoration-none d-flex align-items-top px-2'>"+"<span class='material-symbols-outlined me-2'>picture_as_pdf</span>"+""+description+""+"</label>"+"<div class='light-sm-txt d-block d-flex align-items-top datetime mt-1 px-2 mb-2'>"+"<span class='material-symbols-outlined me-1'>schedule</span>"+""+fromDate+""+"</div>"+"<div class='multiplepdflist d-flex align-items-center px-2'>"+"<ul class='d-flex align-items-top p-0 my-2'>"+"<li class='me-4'>"+"<a href='"+fileURL+"' target='_blank'  class='d-flex align-items-center align-items-top text-decoration-none'>"+"<span class='material-symbols-outlined me-1'>picture_as_pdf</span>"+""+showFileName+""+"</a>"+"</li>"+"</ul>"+"</div>";if(groupId===0){datalistId1.appendChild(newListItem)}
if(groupId==14){datalistId2.appendChild(newListItem)}
if(groupId==14){datalistId3.appendChild(newListItem)}
if(groupId==14){datalistId4.appendChild(newListItem)}}
function languageChange(){localStorage.setItem('siteLanguage',$('#lang').val());initLanguageLabels();document.getElementById("menu").innerHTML='';createMenu(menuData.menu,document.getElementById("menu"));initAfterMenuJsonLoad();let ctMenuTypeVal=localStorage.getItem('ctMenuType');let ctMenuIdVal=localStorage.getItem('ctMenuId');if(ctMenuTypeVal=='parray'){goToParentPage(ctMenuIdVal)}else{if(ctMenuIdVal){const menuDataVal=menuData.menu?menuData.menu:menuData;const menuObjVal=findMenuById(ctMenuIdVal,menuDataVal);var contentType=menuObjVal.contentType;if(contentType=="url"&&menuObj.url!=undefined&&menuObj.url!=''&&menuObj.url!='#')
setMenuDetailsByMenuId(menuObjVal);}}}
function getMenuTitleByLang(menuObj){if($("#lang").val()==='en'){return menuObj.title}else{return menuObj.titleHindi?menuObj.titleHindi:menuObj.title}}
function getMenuContentByLang(menuObj){var content='';if($("#lang").val()==='en'){content=menuObj.encodedContent}else{content=menuObj.encodedContentHindi?menuObj.encodedContentHindi:menuObj.encodedContent}
return decodeURIComponent(escape(atob(content)))}
function getMenuTitleByLangWithTitles(title,hindiTitle){var content='';if($("#lang").val()==='en'){content=title}else{content=hindiTitle?hindiTitle:title}
return content}
function createMenu(menuItems,parentElement){console.log("inside >>createMenu ");menuItems.forEach(item=>{let li=document.createElement("li");let a=document.createElement("a");a.setAttribute('data-submenu-id',item.menuId);a.setAttribute('data-submenu-type',item.contentType);a.href=item.url;a.textContent=getMenuTitleByLang(item);li.appendChild(a);if(item.submenu&&item.submenu.length>0){let ul=document.createElement("ul");createMenu(item.submenu,ul);li.appendChild(ul)}
parentElement.appendChild(li)})}