
<!DOCTYPE html>
<%@page import="formFlowX.fb.FormFlowXCommonFB"%>
c
<%@page import="hisglobal.security.TokenConfig"%>
<%@page import="formFlowX.vo.FormFlowXUserVO"%>
<%@page import="hissso.config.HISSSOConfig"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html lang="en">
<head>
  <title>seach by Trackingid</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
 
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.3/xlsx.full.min.js"></script>

    <script src="script.js"></script>
  <jsp:include page="/global/jsp/commonLayout.jsp" flush="true"></jsp:include>
   <style>
        .highlight {
            background-color: yellow; /* Change this to your preferred highlight color */
        }
    </style>
  
<head>
<script>

</script>
<script type="text/javascript" src="/CGHSCardMgmt/cghsCard/js/Bharatkoshpaymentstatus.js"></script>
  <script type="text/javascript">

   
    </script>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>


<%
  		FormFlowXCommonFB fb=(FormFlowXCommonFB ) request.getAttribute("FORMBEAN");
          	  String isGlobal=fb.getIsGlobal(); 
           		if(isGlobal==null)
          	 		isGlobal="0";
          %>
  
<body>

<form action="/CGHSCardMgmt/FormFlowXACTION" name="FormFlowXACTION" method="post">
<fieldset  class='p-5' id="ENTRYFORM">

 <div class="container-fluid">
 <div class="row" id='divBenID'>
  
    <div class="col-sm-2">
        <div class="form-group">
            <label class="col-form-label col-form-label-md" for="PatTrackingid">Tracking Id :</label>
            <input type="text" class="form-control form-control-sm" id="PatTrackingid" name="PatTrackingid" 
                placeholder="Enter Tracking Id" data-validation="mandatory,numeric" maxlength="20" >
            <div class="invalid-feedback"></div>
       </div>
    </div>
     <div class="col-lg-6 mt-4" >
        <div class="form-group">            
         <button class='btn btn-his ' id="BTNNEXT"  onclick="getfamilydetails()"><i class='fas fa-save fa-fw'></i>&nbsp;Search</button>	
            <div class="invalid-feedback"></div>
        </div>
 	</div> 
 
 	
 	
    
</div>
</div>

   
   
   
<div class="table-responsive" id="PaymentDetail" style="display:none;">
 <h4>Bharatkosh Payment Details</h4>
  <table class="table table-bordered table-striped" >
  <thead>
    <tr>
     <tr>
     <th style="width:5%"><b>S.No</b></th>
       <th style="width:10%">Tracking Id</th>
        <th style="width:10%">Ben Id</th>
       <th style="width:15%">Name</th>
       <th style="width:10%">Card Type</th>
        <th style="width:10%">Mobile Number</th>
         <th style="width:10%">Amount </th>
         <th style="width:10%">UTR No.</th>
        <th style="width:10%">Order Code</th>
	 <th style="width:10%">Payment Status</th>
	 <th style="width:10%">Action</th>
    </tr>
        
	 
    </tr>
	</thead>
	<tbody>
   
	</tbody>
   </table>
   </div>

 <div id="instructionArea" class="container mt-5" style="margin-left: 5%;">
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Status</th>
          <th>Significance</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Submitted</td>
          <td>Beneficiary has reached the Confirm Info screen on NTRP but has not confirmed the payment details.</td>
        </tr>
        <tr>
          <td>Incomplete</td>
          <td>Beneficiary pressed Back or closed the browser while on the Confirm Info screen.</td>
        </tr>
        <tr>
          <td>Confirmed</td>
          <td>Beneficiary confirmed details; redirect to Payment Selection page but did not select a gateway.</td>
        </tr>
        <tr>
          <td>Payment Initiated</td>
          <td>Gateway chosen; user redirected to PG site.</td>
        </tr>
        <tr>
          <td>SUCCESS</td>
          <td>Amount credited, challan generated by NTRP.</td>
        </tr>
        <tr>
          <td>FAIL</td>
          <td>Payment failed at PG; amount not debited or auto-reversed.</td>
        </tr>
        <tr>
          <td>Status Unknown / Abort</td>
          <td>User abandoned on PG page; PG unable to return a definitive status.</td>
        </tr>
        <tr>
          <td>BOOKED (Corporate Net-Banking)</td>
          <td>Maker has completed payment but checker has not authorized yet.</td>
        </tr>
        <tr>
          <td>No records found</td>
          <td>PG has no record of the queried transaction.</td>
        </tr>
        <tr>
          <td>PENDING</td>
          <td>User stopped mid-way at bank/login page; debit may or may not have occurred.</td>
        </tr>
        <tr>
          <td>Failed or Refund If Received</td>
          <td>PG could not confirm status within 30 min of posting.</td>
        </tr>
        <tr>
          <td>Refund Settled</td>
          <td>PG has credited refund to user's account.</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

 <input type="hidden" name="BenId" id="BenId" />
   <input type='hidden' name="Benidvalue" id='Benidvalue' value="<%=request.getParameter("Benidvalue")%>"  /> 
    <input type="hidden" name="statusflag" id="statusflag" value=""/>
    
 
</fieldset>

            <input type="hidden" name="masterKey" id="masterKey" />
	     <input type='hidden' name="hmode" id="hmode"/>
	         <input type="hidden" name="isGlobal" id='isGlobalLocalVar' value="<%=isGlobal%>"/>
	     <input type='hidden' name="tid" id='tid'/>	
	     <input type='hidden' name="initMode" id='initMode' />	     	     		
	     <input type='hidden' name="primaryKeys" id='primaryKeys' />     
	    <%String primaryKeyFromListPage=(String) request.getSession().getAttribute("SEATID");
	       if(primaryKeyFromListPage==null){
	    	   primaryKeyFromListPage="";
	       }	     	
	     %>
	     <input type='hidden' name="primaryKeyFromListPage" id='primaryKeyFromListPage' value="<%=primaryKeyFromListPage %>"  />  
</form>

                                                                  