function isExcludedElement(element){if(element.closest('#uw-main')||element.classList.contains('uwaw-features__item__name')||element.classList.contains('ux4g-text-spacing')||element.classList.contains('feature-image')||element.classList.contains('icon_global')||element.classList.contains('copyright-text')||element.classList.contains('ux4g-copy')){return!0}
if(element.tagName==='SCRIPT'||element.tagName==='DIV'||element.tagName==='LINK'||element.tagName==='HTML'||element.tagName==='HEAD'||element.tagName==='BODY'||(element.tagName==='svg'&&element.namespaceURI==='http://www.w3.org/2000/svg')){return!0}
return!1}
function handleFontSizes(btnId,featureItemId,featureStepsId,tickIconId,increase,btn){var Storageclick=btn+'-clickCount';var ButtonStorageClick=btn+'-buttonClicked';var SizeStorage=btn+'-size';var clickCount=0;var addsize=0;var localStorageClickCount=localStorage.getItem(Storageclick);if(localStorageClickCount){clickCount=parseInt(localStorageClickCount,10)}
document.addEventListener('DOMContentLoaded',function(){var featureItem=document.getElementById(featureItemId);var featureSteps=document.getElementById(featureStepsId);var tickIcon=document.getElementById(tickIconId);var FontSizeBtnState=JSON.parse(localStorage.getItem(ButtonStorageClick));var FontSizeClickState=JSON.parse(localStorage.getItem(Storageclick));var FontSizeStateBigger=localStorage.getItem('bt-size');var FontSizeStateSmaller=localStorage.getItem('st-size');if(FontSizeBtnState){featureItem.classList.add('feature-active');featureSteps.classList.add('featureSteps-visible');tickIcon.style.display='inline-block';var StoragestepsHTML='';for(var i=0;i<4;i++){StoragestepsHTML+='<span class="'+(i<FontSizeClickState?'active step uwaw-features__step':'step uwaw-features__step')+'"></span>'}
featureSteps.innerHTML=StoragestepsHTML;if(FontSizeStateBigger!=0){document.getElementById('btn-small-text').disabled=!0;var elements=document.querySelectorAll('*:not(.uw-widget-custom-trigger, .uw-widget-custom-trigger span)');elements.forEach(function(element){if(!isExcludedElement(element)){var currentSize=window.getComputedStyle(element).fontSize;var newSize=parseFloat(currentSize)+parseFloat(FontSizeStateBigger);element.style.setProperty('font-size',newSize+'px','important')}})}
if(FontSizeStateSmaller!=0){document.getElementById('btn-s9').disabled=!0;var elements=document.querySelectorAll('*:not(.uw-widget-custom-trigger, .uw-widget-custom-trigger span)');elements.forEach(function(element){if(!isExcludedElement(element)){var currentSize=window.getComputedStyle(element).fontSize;var newSize=parseFloat(currentSize)-parseFloat(FontSizeStateSmaller);element.style.setProperty('font-size',newSize+'px','important')}})}}});document.getElementById(btnId).addEventListener('click',function(){clickCount++;addsize+=2;var featureItem=document.getElementById(featureItemId);var featureSteps=document.getElementById(featureStepsId);var tickIcon=document.getElementById(tickIconId);if(btnId=="btn-s9"){document.getElementById('btn-small-text').disabled=!0;localStorage.setItem('btn-big',!0)}
if(btnId=="btn-small-text"){document.getElementById('btn-s9').disabled=!0;localStorage.setItem('btn-small',!0)}
localStorage.setItem(Storageclick,clickCount);localStorage.setItem(ButtonStorageClick,!0);if(clickCount===5){clickCount=0;addsize=0;featureItem.classList.remove('feature-active');featureSteps.classList.remove('featureSteps-visible');featureSteps.innerHTML='';tickIcon.style.display='none';localStorage.setItem(Storageclick,0);localStorage.setItem(ButtonStorageClick,!1);if(btnId=="btn-s9"){document.getElementById('btn-small-text').disabled=!1;localStorage.setItem('btn-big',!1)}
if(btnId=="btn-small-text"){var otherBtn=document.getElementById('btn-s9').disabled=!1;localStorage.setItem('btn-small',!1)}
resetFontSizes(btn,Storageclick,ButtonStorageClick);return}
if(clickCount===1){featureItem.classList.add('feature-active');featureSteps.classList.add('featureSteps-visible');localStorage.setItem(Storageclick,clickCount);localStorage.setItem(ButtonStorageClick,!0)}
document.getElementById(btnId).setAttribute('data-uw-reader-content',clickCount);var stepsHTML='';for(var i=0;i<4;i++){stepsHTML+='<span class="'+(i<clickCount?'active step uwaw-features__step':'step uwaw-features__step')+'"></span>'}
featureSteps.innerHTML=stepsHTML;if(clickCount<5){tickIcon.style.display='inline-block'}
adjustFontSizes(increase,btn,addsize)})}
function adjustFontSizes(increase,btn,addsize){var SizeStorage=btn+'-size';var elements=document.querySelectorAll('*:not(.uw-widget-custom-trigger, .uw-widget-custom-trigger span)');elements.forEach(function(element){if(!isExcludedElement(element)){var currentSize=window.getComputedStyle(element).fontSize;var newSize=increase?parseFloat(currentSize)+2:parseFloat(currentSize)-2;element.style.setProperty('font-size',newSize+'px','important');localStorage.setItem(SizeStorage,parseFloat(addsize))}})}
function resetFontSizes(){var elements=document.querySelectorAll('*');elements.forEach(function(element){element.style.fontSize='';localStorage.setItem('st-size',0);localStorage.setItem('st-clickCount',0);localStorage.setItem('st-buttonClicked',!1);localStorage.setItem('bt-size',0);localStorage.setItem('bt-clickCount',0);localStorage.setItem('bt-buttonClicked',!1);localStorage.setItem('btn-big',!1);localStorage.setItem('btn-small',!1)})}
handleFontSizes('btn-s9','featureItem','featureSteps','tickIcon',!0,'bt');handleFontSizes('btn-small-text','featureItem-st','featureSteps-st','tickIcon-st',!1,'st');let letterSpacing=0;let clickCountText=0;var localStorageSpacingCount=localStorage.getItem('ts-clickCount');if(localStorageSpacingCount){clickCountText=parseInt(localStorageSpacingCount,10)}
function increaseAndReset(){clickCountText++;var featureItem_ts=document.getElementById('featureItem-ts');var featureSteps_ts=document.getElementById('featureSteps-ts');var tickIcon_ts=document.getElementById('tickIcon-ts');localStorage.setItem('ts-clickCount',clickCountText);localStorage.setItem('ts-buttonClicked',!0);if(clickCountText===4){letterSpacing=0;clickCountText=0;featureItem_ts.classList.remove('feature-active');featureSteps_ts.classList.remove('featureSteps-visible');featureSteps_ts.innerHTML='';tickIcon_ts.style.display='none';localStorage.setItem('ts-clickCount',clickCountText);localStorage.setItem('ts-buttonClicked',!1);resetLetterspacing();return}
if(clickCountText===1){featureItem_ts.classList.add('feature-active');featureSteps_ts.classList.add('featureSteps-visible');localStorage.setItem('ts-clickCount',clickCountText);localStorage.setItem('ts-buttonClicked',!0)}
var stepsHTML_ts='';for(var i=0;i<3;i++){stepsHTML_ts+='<span class="'+(i<clickCountText?'active step uwaw-features__step':'step uwaw-features__step')+'"></span>'}
featureSteps_ts.innerHTML=stepsHTML_ts;if(clickCountText<4){tickIcon_ts.style.display='inline-block'}
letterSpacing+=0.7;applyLetterSpacing()}
function decreaseSpacing(){letterSpacing-=5;applyLetterSpacing()}
function applyLetterSpacing(){const elements=document.querySelectorAll('*:not(.uw-widget-custom-trigger, .uw-widget-custom-trigger span)');elements.forEach(function(element){if(!isExcludedElement(element)){var currentSize_ts=parseFloat(window.getComputedStyle(element).letterSpacing);currentSize_ts=isNaN(currentSize_ts)?0:currentSize_ts;currentSize_ts=currentSize_ts+'px';var newSize_ts=parseFloat(currentSize_ts)+0.7;element.style.setProperty('letter-spacing',newSize_ts+'px','important');localStorage.setItem('ts-spacing',parseFloat(newSize_ts))}})}
function resetLetterspacing(){var elements=document.querySelectorAll('*:not(.uw-widget-custom-trigger, .uw-widget-custom-trigger span)');elements.forEach(function(element){element.style.letterSpacing='';localStorage.setItem('ts-spacing',null);localStorage.setItem('ts-clickCount',0);localStorage.setItem('ts-buttonClicked',!1)})}
document.addEventListener('DOMContentLoaded',function(){var featureItem_ts=document.getElementById('featureItem-ts');var featureSteps_ts=document.getElementById('featureSteps-ts');var tickIcon_ts=document.getElementById('tickIcon-ts');var SpacingState=JSON.parse(localStorage.getItem('ts-buttonClicked'));var SpacingClickState=JSON.parse(localStorage.getItem('ts-clickCount'));var SpacingSizeState=localStorage.getItem('ts-spacing');console.log(SpacingSizeState);if(SpacingState){tickIcon_ts.style.display='inline-block';featureItem_ts.classList.add('feature-active');featureSteps_ts.classList.add('featureSteps-visible');var stepsHTML_ts='';for(var i=0;i<3;i++){stepsHTML_ts+='<span class="'+(i<SpacingClickState?'active step uwaw-features__step':'step uwaw-features__step')+'"></span>'}
featureSteps_ts.innerHTML=stepsHTML_ts;const elements=document.querySelectorAll('*:not(.uw-widget-custom-trigger, .uw-widget-custom-trigger span)');elements.forEach(function(element){if(!isExcludedElement(element)){element.style.setProperty('letter-spacing',SpacingSizeState+'px','important')}})}});var clickCount_lh=0;var localStorageClickCount=localStorage.getItem('lh-clickCount');if(localStorageClickCount){clickCount_lh=parseInt(localStorageClickCount,10)}
document.getElementById('btn-s12').addEventListener('click',function(){clickCount_lh++;var featureItem_lh=document.getElementById('featureItem-lh');var featureSteps_lh=document.getElementById('featureSteps-lh');var tickIcon_lh=document.getElementById('tickIcon-lh');localStorage.setItem('lh-clickCount',clickCount_lh);localStorage.setItem('lh-buttonClicked',!0);if(clickCount_lh===4){clickCount_lh=0;featureItem_lh.classList.remove('feature-active');featureSteps_lh.classList.remove('featureSteps-visible');featureSteps_lh.innerHTML='';tickIcon_lh.style.display='none';localStorage.setItem('lh-clickCount',0);localStorage.setItem('lh-buttonClicked',!1);resetlineheight();return}
if(clickCount_lh===1){featureItem_lh.classList.add('feature-active');featureSteps_lh.classList.add('featureSteps-visible');localStorage.setItem('lh-clickCount',1);localStorage.setItem('lh-buttonClicked',!0)}
document.getElementById('btn-s12').setAttribute('data-uw-reader-content',clickCount_lh);var stepsHTML_lh='';for(var i=0;i<3;i++){stepsHTML_lh+='<span class="'+(i<clickCount_lh?'active step uwaw-features__step':'step uwaw-features__step')+'"></span>'}
featureSteps_lh.innerHTML=stepsHTML_lh;if(clickCount_lh<4){tickIcon_lh.style.display='inline-block'}
increaseLineheight()});function increaseLineheight(){var elements=document.querySelectorAll('*:not(.uw-widget-custom-trigger, .uw-widget-custom-trigger span)');elements.forEach(function(element){if(!isExcludedElement(element)){var currentSize_lh=parseFloat(window.getComputedStyle(element).lineHeight);currentSize_lh=isNaN(currentSize_lh)?0:currentSize_lh;currentSize_lh=currentSize_lh+'px';var newSize_lh=parseFloat(currentSize_lh)+10+'px';localStorage.setItem('lh-height',parseFloat(newSize_lh));element.style.setProperty('line-height',newSize_lh,'important')}})}
function resetlineheight(){var elements=document.querySelectorAll('*');elements.forEach(function(element){element.style.lineHeight='';localStorage.setItem('lh-height',null);localStorage.setItem('lh-clickCount',0);localStorage.setItem('lh-buttonClicked',!1)})}
document.addEventListener('DOMContentLoaded',function(){var featureItem_lh=document.getElementById('featureItem-lh');var featureSteps_lh=document.getElementById('featureSteps-lh');var tickIcon_lh=document.getElementById('tickIcon-lh');var LineHeightState=JSON.parse(localStorage.getItem('lh-buttonClicked'));var LineHeightClickState=JSON.parse(localStorage.getItem('lh-clickCount'));var LineHeightSizeState=localStorage.getItem('lh-height');if(LineHeightState){tickIcon_lh.style.display='inline-block';featureItem_lh.classList.add('feature-active');featureSteps_lh.classList.add('featureSteps-visible');var stepsHTML_lh='';for(var i=0;i<3;i++){stepsHTML_lh+='<span class="'+(i<LineHeightClickState?'active step uwaw-features__step':'step uwaw-features__step')+'"></span>'}
featureSteps_lh.innerHTML=stepsHTML_lh;var elements=document.querySelectorAll('*');elements.forEach(function(element){if(!isExcludedElement(element)){var currentSize_lh=parseFloat(window.getComputedStyle(element).lineHeight);currentSize_lh=isNaN(currentSize_lh)?0:currentSize_lh;currentSize_lh=currentSize_lh+'px';var newSize_lh=parseFloat(currentSize_lh)+parseFloat(LineHeightSizeState)+'px';element.style.setProperty('line-height',newSize_lh,'important')}})}});function toggleImages(){document.documentElement.classList.toggle('image-hide');document.documentElement.id=document.documentElement.classList.contains('image-hide')?'imageHideBg':'';var images=document.querySelectorAll('img');var imageVisibilityState={};var tickIcon_ht=document.getElementById('tickIcon-hi');var featureItem=document.getElementById('featureItem-hi');images.forEach(function(image,index){if(!isExcludedElement(image)){image.style.setProperty('visibility',image.style.visibility==='hidden'?'visible':'hidden','important');imageVisibilityState[index]=image.style.visibility}});tickIcon_ht.style.display=tickIcon_ht.style.display==='none'?'inline-block':'none';featureItem.classList.toggle('feature-active');localStorage.setItem('imageVisibilityState',JSON.stringify(imageVisibilityState))}
document.addEventListener('DOMContentLoaded',function(){var tickIcon_ht=document.getElementById('tickIcon-hi');var featureItem=document.getElementById('featureItem-hi');var images=document.querySelectorAll('img');var imageVisibilityState=JSON.parse(localStorage.getItem('imageVisibilityState'));if(imageVisibilityState){images.forEach(function(image,index){if(!isExcludedElement(image)&&imageVisibilityState[index]){image.style.setProperty('visibility',imageVisibilityState[index],'important')}})}
if(imageVisibilityState&&imageVisibilityState['1']==='hidden'){tickIcon_ht.style.display='inline-block';featureItem.classList.add('feature-active');document.documentElement.classList.toggle('image-hide');document.documentElement.id=document.documentElement.classList.contains('image-hide')?'imageHideBg':''}});document.getElementById('dark-btn').addEventListener('click',function(){var tickIcon_ht_dark=document.getElementById('tickIcon-ht-dark');var featureItemDrak=document.getElementById('featureItem-ht-dark');const checkbox=document.getElementById("checkbox");const isDarkMode=checkbox.checked;document.body.classList.toggle("dark",isDarkMode);tickIcon_ht_dark.style.display=tickIcon_ht_dark.style.display==='none'?'inline-block':'none';featureItemDrak.classList.toggle('feature-active');localStorage.setItem("darkMode",isDarkMode)});document.addEventListener('DOMContentLoaded',function(){var tickIcon_ht_dark=document.getElementById('tickIcon-ht-dark');var featureItemDrak=document.getElementById('featureItem-ht-dark');const checkbox=document.getElementById("checkbox");const isDarkMode=JSON.parse(localStorage.getItem('darkMode'));if(isDarkMode===!0){checkbox.checked=isDarkMode;document.body.classList.add("dark");tickIcon_ht_dark.style.display='inline-block';featureItemDrak.classList.toggle('feature-active')}});function highlightLinks(){var tickIcon_ht=document.getElementById('tickIcon-ht');var featureItem=document.getElementById('featureItem-ht');tickIcon_ht.style.display=tickIcon_ht.style.display==='none'?'inline-block':'none';featureItem.classList.toggle('feature-active');var links=document.querySelectorAll('a');var linksHighlighted=!1;links.forEach(function(link,index){if(!isExcludedElement(link)){link.style.setProperty('background',link.style.background?'':'black','important');link.style.setProperty('color',link.style.color?'':'yellow','important');if(link.style.getPropertyValue('background')==='black'&&link.style.getPropertyValue('color')==='yellow'){linksHighlighted=!0}}});var HighlightLinkState={tickIconVisible:tickIcon_ht.style.display==='none'?!1:!0,featureActive:featureItem.classList.contains('feature-active'),linksHighlighted:linksHighlighted};localStorage.setItem("highlightLinks",JSON.stringify(HighlightLinkState))}
document.addEventListener('DOMContentLoaded',function(){var tickIcon_ht=document.getElementById('tickIcon-ht');var featureItem=document.getElementById('featureItem-ht');var links=document.querySelectorAll('a');var GetHighlightLinkState=JSON.parse(localStorage.getItem('highlightLinks'));if(GetHighlightLinkState){if(GetHighlightLinkState.tickIconVisible){tickIcon_ht.style.display='inline-block'}else{tickIcon_ht.style.display='none'}
if(GetHighlightLinkState.featureActive){featureItem.classList.add('feature-active')}else{featureItem.classList.remove('feature-active')}
if(GetHighlightLinkState.linksHighlighted){links.forEach(function(link,index){if(!isExcludedElement(link)&&GetHighlightLinkState){link.style.setProperty('background','#1C1D1F','important');link.style.setProperty('color','yellow','important')}})}}});function toggleCursorFeature(){document.documentElement.classList.toggle('ux4g-bg-cursor');var tickIcon_cursor=document.getElementById('tickIcon-cursor');tickIcon_cursor.style.display=tickIcon_cursor.style.display==='none'?'inline-block':'none';var featureItem=document.getElementById('featureItem-Cursor');featureItem.classList.toggle('feature-active');localStorage.setItem("cursorFeatureActive",featureItem.classList.contains('feature-active'))}
document.addEventListener('DOMContentLoaded',function(){var GetCursorState=JSON.parse(localStorage.getItem('cursorFeatureActive'));var tickIcon_cursor=document.getElementById('tickIcon-cursor');var featureItem=document.getElementById('featureItem-Cursor');if(GetCursorState===!0){document.documentElement.classList.add('ux4g-bg-cursor');tickIcon_cursor.style.display='inline-block';featureItem.classList.add('feature-active')}});function toggleFontFeature(){document.documentElement.classList.toggle('ux4g-font-df');var tickIcon_df=document.getElementById('tickIcon-df');tickIcon_df.style.display=tickIcon_df.style.display==='none'?'inline-block':'none';var featureItem=document.getElementById('featureItem-df');featureItem.classList.toggle('feature-active');localStorage.setItem("dyslexia",document.documentElement.classList.contains('ux4g-font-df'))}
document.addEventListener('DOMContentLoaded',function(){var GetdyslexiaState=JSON.parse(localStorage.getItem('dyslexia'));var tickIcon_df=document.getElementById('tickIcon-df');var featureItem_df=document.getElementById('featureItem-df');if(GetdyslexiaState===!0){document.documentElement.classList.add('ux4g-font-df');tickIcon_df.style.display='inline-block';featureItem_df.classList.add('feature-active')}});document.getElementById('btn-invert').addEventListener('click',function(){document.documentElement.classList.toggle('ux4g-bg-white');var tickIcon_ic=document.getElementById('tickIcon-ic');tickIcon_ic.style.display=tickIcon_ic.style.display==='none'?'inline-block':'none';var featureItem=document.getElementById('featureItem-ic');featureItem.classList.toggle('feature-active');localStorage.setItem('invertFeature',document.documentElement.classList.contains('ux4g-bg-white'))});document.addEventListener('DOMContentLoaded',function(){var GetInvertState=JSON.parse(localStorage.getItem('invertFeature'));var tickIcon_ic=document.getElementById('tickIcon-ic');var featureItem_ic=document.getElementById('featureItem-ic');if(GetInvertState===!0){document.documentElement.classList.add('ux4g-bg-white');tickIcon_ic.style.display='inline-block';featureItem_ic.classList.add('feature-active')}});document.getElementById('uw-widget-custom-trigger').addEventListener('click',function(){openMain()});function openMain(){var mainElement=document.getElementById('uw-main');mainElement.style.right='0px'}
function closeMain(){var mainElement=document.getElementById('uw-main');mainElement.style.right='-490px'}
function resetAll(){var resetFeatures=document.querySelectorAll('.reset-feature');resetFeatures.forEach(function(feature){feature.classList.remove('feature-active')});var resetTicks=document.querySelectorAll('.reset-tick');resetTicks.forEach(function(tick){tick.style.display='none'});var links=document.querySelectorAll('a');links.forEach(function(link){link.style.background='';link.style.color=''});localStorage.setItem('highlightLinks',!1);var images=document.querySelectorAll('img');images.forEach(function(image){image.style.visibility='visible'});var resetImageVisibilityState={};localStorage.setItem('imageVisibilityState',JSON.stringify(resetImageVisibilityState));document.documentElement.classList.remove('image-hide');document.documentElement.id=document.documentElement.classList.contains('image-hide')?'imageHideBg':'';document.documentElement.classList.remove('ux4g-bg-white');localStorage.setItem('invertFeature',!1);document.documentElement.classList.remove('ux4g-font-df');localStorage.setItem("dyslexia",!1);document.documentElement.classList.remove('ux4g-bg-cursor');localStorage.setItem("cursorFeatureActive",!1);var reset_check=document.getElementById("checkbox").checked=!1;document.body.classList.remove("dark",reset_check);localStorage.setItem("darkMode",!1);resetlineheight();resetLetterspacing();resetFontSizes();document.getElementById('btn-s9').disabled=!1;document.getElementById('btn-small-text').disabled=!1;var resetSteps=document.querySelectorAll('.reset-steps');resetSteps.forEach(function(step){step.innerHTML='';step.classList.remove('featureSteps-visible')});resetspeech();localStorage.setItem("speak",!1)}
document.getElementById('speak').addEventListener('click',function(){var tickIcon_sp=document.getElementById('tickIcon_sp');tickIcon_sp.style.display=tickIcon_sp.style.display==='none'?'inline-block':'none';var featureItem_sp=document.getElementById('featureItem_sp');featureItem_sp.classList.toggle('feature-active');localStorage.setItem("speak",featureItem_sp.classList.contains('feature-active'))});const speakEl=document.getElementById('speak');let isReading=!1;let utterance=null;let previousSelectedElement=null;const speakOnSound=new Audio('');const speakOffSound=new Audio('');document.addEventListener('mouseup',function(event){if(isReading){const clickedElement=event.target;const allowedTags=['P','SPAN','DIV','H1','H2','H3','H4','H5','H6','A','LI','LABEL','BUTTON','TD','TH','STRONG','EM','B','I','U','SMALL','BIG','SUB','SUP'];if(allowedTags.includes(clickedElement.tagName.toUpperCase())){selectAndSpeak(clickedElement)}}});speakEl.addEventListener('click',toggleSpeech);function toggleSpeech(){if(!isReading){speakOnSound.play();isReading=!0}else{resetspeech()}}
function resetspeech(){speakOffSound.play();window.speechSynthesis.cancel();isReading=!1;previousSelectedElement=null}
function startReading(text){utterance=new SpeechSynthesisUtterance(text);utterance.rate=0.7;utterance.pitch=10.0;const voices=window.speechSynthesis.getVoices();const femaleVoice=voices.find(voice=>voice.name.includes('female')&&voice.lang.includes('en'));if(femaleVoice){utterance.voice=femaleVoice}
window.speechSynthesis.speak(utterance);utterance.addEventListener('end',function(){resetSelection()})}
function selectAndSpeak(element){const range=document.createRange();range.selectNodeContents(element);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);if(previousSelectedElement!==element){window.speechSynthesis.cancel();startReading(selection.toString());previousSelectedElement=element}else{if(isReading){window.speechSynthesis.pause()}else{window.speechSynthesis.resume()}}}
function resetSelection(){const selection=window.getSelection();selection.removeAllRanges();previousSelectedElement=null}
document.addEventListener('DOMContentLoaded',function(){var GetspeakState=JSON.parse(localStorage.getItem('speak'));var tickIcon_sp=document.getElementById('tickIcon_sp');var featureItem_sp=document.getElementById('featureItem_sp');if(GetspeakState===!0){tickIcon_sp.style.display='inline-block';featureItem_sp.classList.add('feature-active');speakOnSound.play();isReading=!0}})